<a href="https://colab.research.google.com/github/abhinxvs/python-code/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
height = [100,200,300,400,500]

sum = 0

for i in height:
  sum+=i

avg = sum/len(height)

print(avg)

300.0


In [3]:
n = int(input('Enter number - '))
if n>1:
  for i in range(2,n):
    if n%i==0:
      print('Number is not prime')
      break
  else:
    print('Number is prime')
else:
  print("Invalid number")

Enter number - 122
Number is not prime


In [6]:
for i in range(3):
  pwd = input('Enter the password - ')
  if pwd=='SECRET':
    print('Access Granted')
    break
  else:
    print('Try Again')
else:
  print('Out of tries')

Enter the password - a
Try Again
Enter the password - a
Try Again
Enter the password - a
Try Again
Out of tries


In [7]:
l = [122,2343,32,22,22922]
largest = l[0]
index = 1

while index<len(l):
  if l[index]>largest:
    largest = l[index]
  index+=1

print(largest)

22922


In [11]:
price = [122,33,22,122,11231,1231]
import numpy as np
a = np.array(price)
print(a)

a = np.sort(a)
print(a)

al = a*2
print(al)

nl = np.multiply(a[a%2==1],0.9)
print(nl)

[  122    33    22   122 11231  1231]
[   22    33   122   122  1231 11231]
[   44    66   244   244  2462 22462]
[   29.7  1107.9 10107.9]


In [12]:
mean = np.mean(price)
print(mean)

median = np.median(price)
print(median)

mode = 0
maxcount = 0

for i in price:
  count = price.count(i)
  if count>maxcount:
    maxcount = count
    mode = i

print(mode)

2126.8333333333335
122.0
122


In [14]:
import pandas as pd
df = pd.DataFrame()
df['Name'] = ['Rohit','Sohit','Lohit']
df['Marks'] = [92,87,72]
print(df)
print(df.Name[1])
print(df.Marks[1])

    Name  Marks
0  Rohit     92
1  Sohit     87
2  Lohit     72
Sohit
87


In [ ]:
import matplotlib.pyplot as plt